name: Next Deployment


on: 
  push:
      branches: [production]


  job:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy using ssh
        user: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
           script: |
             cd /var/www/tpgroup.net
             git fetch origin
             git checkout production
             git pull 
             npm install
            npm run build
             pm2 reload tpgroup  
            
             
